[build]
  base = "career-decision-lab/"
  command = "export DEPLOY_TARGET=netlify && npm run build"
  publish = "career-decision-lab/out"

[build.environment]
  NODE_ENV = "production"
  DEPLOY_TARGET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
